apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-depl
  namespace: argocd
  labels:
    app: pingpong-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-depl
  template:
    metadata:
      labels:
        app: pingpong-depl
    spec:
      containers:
        - name: pingpong
          image: wohligakash/pingpong
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
