apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-depl
  namespace: argocd
  generation: 1
  labels:
    app: pingpong-depl
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-depl
  template:
    metadata:
      labels:
        app: pingpong-depl
    spec:
      containers:
        - name: pingpong
          image: wohligakash/pingpong
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
