apiVersion: v1
kind: Service
metadata:
  name: pingpong-serv
  namespace: argocd
  labels:
    app: pingpong-depl
spec:
  ports:
    - port: 7000
      nodePort: 30666
      targetPort: 7000
  selector:
    app: pingpong-depl
  type: NodePort
