apiVersion: v1
kind: Service
metadata:
  name: pingpong-serv
  namespace: argocd
  labels:
    app: pingpong
status:
  loadBalancer: {}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30003
  selector:
    app: pingpong

