apiVersion: v1
kind: Service
metadata:
  name: pingpong-depl
  namespace: argocd
  resourceVersion: '50809'
  labels:
    app: pingpong-depl
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 7000
      nodePort: 30625
  selector:
    app: pingpong-depl
  type: NodePort
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
